### ISSUE TITLE
Works on 1.8 only?

### ISSUE THREAD

**Issue by agrimm** [seattlerb/zenprofile#1]
I came across this from https://github.com/tmm1/rblineprof (which I haven't tried out yet)

I tried running this under Ruby 1.9, and got

```
agrimm@proline:~/code/project_name$ zenprofile test/my_test.rb
/home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/zenprofile-1.3.2/bin/zenprofile:5: Use RbConfig instead of obsolete and deprecated Config.
/home/agrimm/.ruby_inline/ruby-1.9.1/Inline_EventHook_39933660720e9b6e75d69464894daa04.c:4:18: fatal error: node.h: No such file or directory
compilation terminated.
/home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/RubyInline-3.12.2/lib/inline.rb:616:in `build': error executing "gcc -shared   -fPIC -g -O2  -L. -L'/home/agrimm/.rbenv/versions/1.9.3-p448/lib'  -rdynamic -Wl,-export-dynamic -I /home/agrimm/.rbenv/versions/1.9.3-p448/include/ruby-1.9.1 -I /home/agrimm/.rbenv/versions/1.9.3-p448/include/ruby-1.9.1/x86_64-linux -I /home/agrimm/.rbenv/versions/1.9.3-p448/include -L/home/agrimm/.rbenv/versions/1.9.3-p448/lib -o \"/home/agrimm/.ruby_inline/ruby-1.9.1/Inline_EventHook_39933660720e9b6e75d69464894daa04.so\" \"/home/agrimm/.ruby_inline/ruby-1.9.1/Inline_EventHook_39933660720e9b6e75d69464894daa04.c\"  ": pid 9372 exit 1 (CompilationError)
Renamed /home/agrimm/.ruby_inline/ruby-1.9.1/Inline_EventHook_39933660720e9b6e75d69464894daa04.c to /home/agrimm/.ruby_inline/ruby-1.9.1/Inline_EventHook_39933660720e9b6e75d69464894daa04.c.bad
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/RubyInline-3.12.2/lib/inline.rb:854:in `inline'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/event_hook-1.0.2/lib/event_hook.rb:49:in `<class:EventHook>'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/event_hook-1.0.2/lib/event_hook.rb:4:in `<top (required)>'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/zenprofile-1.3.2/lib/zenprofiler.rb:5:in `<top (required)>'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/zenprofile-1.3.2/lib/zenprofile.rb:1:in `<top (required)>'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/agrimm/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
```

According to a comment by Aaron at https://groups.google.com/forum/#!msg/johnson-talk/mDQOSLsouGc/G25DT2Sr8cgJ about a separate project, node.h isn't available in Ruby 1.9.

Does this mean it doesn't work on Ruby 1.9/2.0?

**Comment by zenspider** [comment]
yup

**Comment by zenspider** [comment]
This project is documented as EOL'd. Closing.
